[fix] alias 변수가 다르던 현상 수정

diff --git a/.github/workflows/flutter-ci-cd.yaml b/.github/workflows/flutter-ci-cd.yaml
--- a/.github/workflows/flutter-ci-cd.yaml
+++ b/.github/workflows/flutter-ci-cd.yaml
@@ -188,15 +188,23 @@ jobs:
 
       - name: ✏️ Create key.properties in app module
         run: |
-          echo "storePassword=${{ env.ANDROID_KEYSTORE_PASSWORD }}" > android/app/key.properties
-          echo "keyPassword=${{ env.ANDROID_KEY_PASSWORD }}" >> android/app/key.properties
-          echo "keyAlias=${{ env.ANDROID_KEY_ALIAS }}" >> android/app/key.properties
-          echo "storeFile=${{ github.workspace }}/keystore.jks" >> android/app/key.properties
+          echo "key.store.password=${{ env.ANDROID_KEYSTORE_PASSWORD }}" > android/app/key.properties
+          echo "key.alias.password=${{ env.ANDROID_KEY_PASSWORD }}" >> android/app/key.properties
+          echo "key.alias.name=${{ env.ANDROID_KEY_ALIAS }}" >> android/app/key.properties
+          echo "key.store.file=${{ github.workspace }}/keystore.jks" >> android/app/key.properties
 
-      - name: 🔍 Debug build.gradle.kts 상단
-        working-directory: android/app
+      - name: 🚨 Gradle 빌드 (에러만 보기)
+        working-directory: android
+        shell: bash
         run: |
-          sed -n '1,100p' build.gradle.kts
+          chmod +x gradlew
+          # 1) 빌드 로그 남기기
+          ./gradlew bundleRelease --stacktrace --console=plain 2>&1 | tee build.log || true
+
+          # 2) 에러 블록만 출력
+          awk '/^FAILURE: Build failed/{flag=1} flag' build.log
+          # exit code는 이전 빌드 결과를 그대로 전달
+          grep -q "BUILD FAILED" build.log && exit 1 || exit 0
 
       - name: 🧩 Shorebird Patch
         id: shorebird-patch
@@ -209,8 +217,6 @@ jobs:
         with:
           platform: android
           args: "--verbose --track=staging"
-
-
 
   # # ios shorebird release
   # release-ios:
